$(document).ready(   
function(){$('#speedzakaz').hide();$('#voprozad').hide();$('#voprozad2').hide();$('#speedclick').toggle(function(){$('#speedzakaz').slideDown(1000);},function(){$('#speedzakaz').slideUp(2000);});$('#voprozadclick').toggle(function(){$('#voprozad').slideDown(1000);},function(){$('#voprozad').slideUp(2000);});$('#izmc').toggle(function(){$('#voprozad2').slideDown(100);},function(){$('#voprozad2').slideUp(2000);});$('.imageitems img').attr('height',120).attr('width',160);$('.levlcat img').attr('height',100).attr('width',140);$('#small img').attr('height',90).attr('width',110);$('.look img').attr('height',120).attr('width',160);$('.opis_punct:even').addClass('bs');var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-39713687-1']);
_gaq.push(['_addOrganic', 'images.yandex.ru','q',true]);
_gaq.push(['_addOrganic', 'blogsearch.google.ru','q',true]);
_gaq.push(['_addOrganic', 'blogs.yandex.ru','text', true]);
_gaq.push(['_addOrganic', 'go.mail.ru','q']);
_gaq.push(['_addOrganic', 'nova.rambler.ru','query']);
_gaq.push(['_addOrganic', 'nigma.ru','s']);
_gaq.push(['_addOrganic', 'webalta.ru','q']);
_gaq.push(['_addOrganic', 'aport.ru','r']);
_gaq.push(['_addOrganic', 'poisk.ru','text']);
_gaq.push(['_addOrganic', 'km.ru','sq']);
_gaq.push(['_addOrganic', 'liveinternet.ru','ask']);
_gaq.push(['_addOrganic', 'quintura.ru','request']);
_gaq.push(['_addOrganic', 'search.qip.ru','query']);
_gaq.push(['_addOrganic', 'gde.ru','keywords']);
_gaq.push(['_addOrganic', 'gogo.ru','q']);
_gaq.push(['_addOrganic', 'ru.yahoo.com','p']);
_gaq.push(['_addOrganic', 'market.yandex.ru','text', true]);
_gaq.push(['_addOrganic', 'price.ru','pnam']);
_gaq.push(['_addOrganic', 'tyndex.ru','pnam']);
_gaq.push(['_addOrganic', 'torg.mail.ru','q']);
_gaq.push(['_addOrganic', 'tiu.ru','query']);
_gaq.push(['_addOrganic', 'tech2u.ru','text']);
_gaq.push(['_addOrganic', 'goods.marketgid.com','query']);
_gaq.push(['_addOrganic', 'poisk.ngs.ru','q']);
_gaq.push(['_addOrganic', 'akavita.by','z']);
_gaq.push(['_addOrganic', 'tut.by','query']);
_gaq.push(['_addOrganic', 'all.by','query']);
_gaq.push(['_addOrganic', 'meta.ua','q']);
_gaq.push(['_addOrganic', 'bigmir.net','q']);
_gaq.push(['_addOrganic', 'i.ua','q']);
_gaq.push(['_addOrganic', 'online.ua','q']);
_gaq.push(['_addOrganic', 'a.ua','s']);
_gaq.push(['_addOrganic', 'ukr.net','search_query']);
_gaq.push(['_addOrganic', 'search.com.ua','q']);
_gaq.push(['_addOrganic', 'search.ua','query']);
_gaq.push(['_addOrganic', 'search.ukr.net','search_query']);
_gaq.push(['_addOrganic', 'sm.aport.ru','r']);
_gaq.push(['_setSampleRate', '80']);
_gaq.push(['_setCampTermKey', 'term']);
  _gaq.push(['_trackPageview']);
setTimeout('if (window._gaq != undefined) _gaq.push([\'_trackEvent\', \'NoBounce\', \'Over 60 seconds\'])',60000);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();});